name: golangci-lint
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches:
      - main
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        working-directory:
          - ""
          - tools/setup-envtest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3.5.0
        with:
          go-version: "1.19"
          check-latest: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51.1
          working-directory: ${{matrix.working-directory}}
